<div class="outerbox"><div class="innerbox">
<div class="innerbox-top"><?php echo $this->translate("Community");?></div>
     <div class="innerbox-bg">
    <?php $this->headTitle()->append("Community");?>
     <h2><?php echo $this->translate("Interactive and relevant geographically
		Perhaps better to just let people post things here by region.  They would submit to us and we would post them like an administrator does         with a Yahoo group.");?></h2>
     
 <ul>
 <li><?php echo $this->translate("Forum Topics");?></li>
 <li><?php echo $this->translate("Categorize information by region and list events and activities taking place in that region");?></li>
 <li><?php echo $this->translate("Calendar posts that users can post events and clinics, horse shows on ");?></li>
 <li><?php echo $this->translate("Vacation rentals- links to VRBO  in horse areas, such as Southern Pines, NC, Western NC, Ocala, FL, Aiken, SC, Wellington, FL, Woodstock, VT, HITS on the Hudson,  Gladstone, NJ, Alabama or Mississippi, wherever Gretchen goes in the winter");?></li>
 </ul>
     </div>
     <div class="innerbox-botm"></div>
     </div></div>
