<div class="outerbox"><div class="innerbox">
<div class="innerbox-top"><?php echo $this->translate("Our Business Partners");?></div>
     <div class="innerbox-bg">
    <?php $this->headTitle()->append("Our Business Partners");?>
     
      <p><?php echo $this->translate("Farside Farm
		Black Diamond Farm
		Broadstone Equine Insurance
		Smart Pak
		Tractor Supply 
		Peterson Equine Video Productions ");?></p>
		
     </div>
     <div class="innerbox-botm"></div>
     </div></div>
