<div class="outerbox"><div class="innerbox">
<div class="innerbox-top"><?php echo $this->translate("Take A Tour");?></div>
     <div class="innerbox-bg">
    <?php $this->headTitle()->append("Take A Tour");?>
     
      <p><?php echo $this->translate("We want the OSH site to be your resource for all of your most important equine information.  Our goal is to make it extremely easy for you to use, no matter how much or how little computer experience you have.  So, if there is something that will help you to manage your horses, barn or activities better, we want to know.  Just drop us a line and share your ideas and suggestions with us so we can make OSH the best equine management tool for you and your horses, minis, donkeys and other members of the equine family. ")?>

     </div>
     <div class="innerbox-botm"></div>
     </div></div>