<table width="100%" cellspacing="0" cellpadding="0">
<?php
    $datas = $this->data;
	?>
    <tr>
	  <td>First Name&nbsp;&nbsp;</td>
	  <td><?php echo $datas['namePerson/first']; ?></td>	
	 </tr>
	 <tr>
	  <td>Last Name&nbsp;&nbsp;</td> 
	  <td><?php echo $datas['namePerson/last']; ?></td>
	 </tr> 
	 <tr>
	  <td>Email&nbsp;&nbsp;</td> 
	  <td><?php echo $datas['contact/email']; ?></td>
	 </tr>   
	 <tr>
	  <td>ID&nbsp;&nbsp;</td>
	  <td><?php echo  $this->identity; ?></td>
	 </tr> 
	  
 <?php 
 
 ?>

  </table>
