<?php  
 echo '<strong>Name</strong>&nbsp; '.$this->escape($this->fullname).'<br>';
 echo '<strong>Nick Name</strong>&nbsp; '.$this->escape($this->nickname).'<br>';
 echo '<strong>Gender</strong>&nbsp; '.$this->escape($this->gender).'<br>';
 echo '<strong>Email</strong>&nbsp; '.$this->escape($this->email).'<br>';
 echo '<strong>DOB.</strong>&nbsp; '.$this->escape($this->dob).'<br>';
 echo '<strong>Language</strong>&nbsp; '.$this->escape($this->language).'<br>';
 echo '<strong>Country</strong>&nbsp; '.$this->escape($this->country).'<br>';
 echo '<strong>Post Code</strong>&nbsp; '.$this->escape($this->postcode).'<br>';
 ?>


