<div class="outerbox"><div class="innerbox"> 
<div class="innerbox-top"><?php echo $this->translate('Reset Password');?></div>
<div class="innerbox-bg">
<div  class="form-detail">
<div>
	 <ul class="errors"><li><?php echo implode("&nbsp; ", $this->messages); ?></li></ul>
	 </div>
<?php echo $this->form;?>
</div>
<div class="cl"></div>
</div>
<div class="innerbox-botm"></div>
</div></div>


