<div class="outerbox"><div class="innerbox"> 
<div class="innerbox-top"><?php echo $this->translate('Forgot Password');?></div>
<div class="innerbox-bg">
<div  class="form-detail">
<div>
	 <ul class="errors"><li><?php echo $this->translate(implode("&nbsp; ", $this->messages)); ?></li></ul>
	 </div>
<strong><label>Security Question :&nbsp;</label><?php echo $this->translate($this->question); ?></strong><br /><br />
<?php echo $this->form;?>
</div>
<div class="cl"></div>
</div>
<div class="innerbox-botm"></div>
</div></div>


