<?php  $css = $this->baseUrl()."/css/fullcalendar/" ;?>
<?php  $js  = $this->baseUrl()."/js/" ;?>
<link rel='stylesheet' type='text/css' href='<?php echo $css ;?>fullcalendar.css' />
<link rel='stylesheet' type='text/css' href='<?php echo $css ;?>fullcalendar.print.css' media='print'/>
<script type='text/javascript' src='<?php echo $js ;?>jquery-1.5.2.min.js'></script>
<script type='text/javascript' src='<?php echo $js ;?>jquery-ui-1.8.11.custom.min.js'></script>
<script type='text/javascript' src='<?php echo $js ;?>fullcalendar/fullcalendar.min.js'></script>
<script type='text/javascript'>
	$(document).ready(function()
	{
		var date = new Date();
		var d = date.getDate();
		var m = date.getMonth();
		var y = date.getFullYear();
		
		$('#calendar').fullCalendar({
			header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,basicWeek,basicDay'
			},
			editable: true,
			events: [
				{
					title: 'All Day Event',
					start: new Date(y, m, 1)
				},
				{
					title: 'Long Event',
					start: new Date(y, m, d-5),
					end: new Date(y, m, d-2)
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d-3, 16, 0),
					allDay: false
				},
				{
					id: 999,
					title: 'Repeating Event',
					start: new Date(y, m, d+4, 16, 0),
					allDay: false
				},
				{
					title: 'Meeting',
					start: new Date(y, m, d, 10, 30),
					allDay: false
				},
				{
					title: 'Lunch',
					start: new Date(y, m, d, 12, 0),
					end: new Date(y, m, d, 14, 0),
					allDay: false
				},
				{
					title: 'Birthday Party',
					start: new Date(y, m, d+1, 19, 0),
					end: new Date(y, m, d+1, 22, 30),
					allDay: false
				},
				{
					title: 'Click for Google',
					start: new Date(y, m, 28),
					end: new Date(y, m, 29),
					url: 'http://google.com/'
				}
			]
		});
		
	});

</script>
<style type='text/css'>
	
	#calendar
	{
		margin: 15px 0px 0 0;
		width: 720px;
	}
</style>
<div id='calendar'></div>
