<?php
	$rows  = $this->paginator ;	
	$sRows  = $this->getvalue ;	
	
	/*
	echo "<pre>";
		print_r($sRows) ;
	echo "</pre>";
	*/
		 
?>

	<script language="javascript">
		function submitfrm()
		{
			
			document.frm.submit();
		}
    </script>

    <br class="clear">
    <div class="listview-month">
   
      <div class="fr">
      <form name="frm" action="<?php echo $this->baseUrl().'/event/listviews'?>"  method="get" >
      <?php
	  
	  	  
		if($_SESSION['getValue']['lyear'] !="")
			$cYear =$_SESSION['getValue']['lyear'] ;
		else
			$cYear = date('Y') ;

		if($_SESSION['getValue']['lmonth'] !="")
			$cMonth =$_SESSION['getValue']['lmonth'] ;
		else
			$cMonth = date('m') ;
			
	   
	   
	  ?>
        <select style="width:115px" name="lmonth" id="lmonth1"  onchange="submitfrm();">
            <option value="1" <?php if($cMonth == "1") {?> selected="selected" <?php } ?> >January</option>
            <option value="2" <?php if($cMonth == "2") {?> selected="selected" <?php } ?> >February</option>
            <option value="3" <?php if($cMonth == "3") {?> selected="selected" <?php } ?> >March</option>
            <option value="4" <?php if($cMonth == "4") {?> selected="selected" <?php } ?> >April</option>
            <option value="5" <?php if($cMonth == "5") {?> selected="selected" <?php } ?> >May</option>
            <option value="6" <?php if($cMonth == "6") {?> selected="selected" <?php } ?> >June</option>
            <option value="7" <?php if($cMonth == "7") {?> selected="selected" <?php } ?> >July</option>
            <option value="8" <?php if($cMonth == "8") {?> selected="selected" <?php } ?> >August</option>
            <option value="9" <?php if($cMonth == "9") {?> selected="selected" <?php } ?> >September</option>
            <option value="10" <?php if($cMonth == "10") {?> selected="selected" <?php } ?> >October</option>
            <option value="11" <?php if($cMonth == "11") {?> selected="selected" <?php } ?> >November</option>
            <option value="12" <?php if($cMonth == "12") {?> selected="selected" <?php } ?> >December</option>
        </select>
            
        <select name="lyear" id="lyear" onchange="submitfrm();">
        	<?php
            for($i = 2000 ; $i < 2021 ; $i++)
			{
			?>
            <option value="<?php echo $i ;?>" <?php if($cYear == $i) {?> selected="selected" <?php } ?>  >
				<?php echo $i ;?>
            </option>
            <?php 
			} 
			?>
        </select>
       </form>   
      </div>
      <br class="clear">
</div>
    
 <div class="event-box">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
  	  		<?php
	  		//echo "AAAAAAAAAAAAAAA ".count($rows);
			if(count($rows) > 0)
			{
			?>
				<tr class="table-heading">
					<td width="50%"><strong>Event Name</strong></td>
					<td width="15%"><strong>Start Date</strong></td>
					<td width="15%"><strong>End Date</strong></td>
					<td><strong>Country</strong></td>
				</tr>
                <?php
				foreach($rows as $row)
				{
					$countryName = '';				
					if(count($row['Med_Model_Countries']) > 0)
						$countryName = $row['Med_Model_Countries']['country_name'];
				?>
                <tr>
                    <td><div style="width:350px; word-wrap:break-word;"><?php echo $row['event_name'] ;?></div></td>
                    <td><?php echo $row['event_start_date'] ;?></td>
                    <td><?php echo $row['event_end_date'] ;?></td>
                    <td><?php echo $countryName ;?></td>
                </tr>
				<?php 
				}// End foreach 
				?>

				<tr class="bottom-bg">
					<td colspan="4" align="center">
						<?php echo $this->paginationControl($this->paginator, 'Sliding',  'listpagination.phtml'); ?>
					</td>
				</tr>
                
                <?php

			}// End If
			else
			{
			?>
				<tr> 
                <td colspan="" style="color:#900" align="center">
                    <b>No records found !!</b>
                </td>
				</tr>
            <?php
			}// End Else
        ?>
        </table>
    </div>