<?php $this->placeholder('sidebar-search')->captureStart() ?>   
     <h2>Search Criteria</h2>
    <form action="" class="search-form">
    <p>Keyword/Phrase</p>
    <p><label><input name="" type="text" /></label></p>
    <p>Event Name</p>
    <p><label><input name="" type="text" /></label></p>
    <p><span class="padding-right">From</span>&nbsp;<select name="" class="calander-fld"></select>&nbsp;<img src="images/calendar-icon.gif" /></p>
     <p><span class="padding-R">To</span>&nbsp;<select name="" class="calander-fld"></select>&nbsp;<img src="images/calendar-icon.gif" /></p>
    <p>Primary Objective</p>
    <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p>Campaign Alignment</p>
     <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p>Customer Target</p>
    <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p>Business Group</p>
     <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p>Industry/Sectors</p>
     <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p>Geography</p>
     <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p>Event Type</p>
     <p><label><select name="" class="search-form-select">
     <option>Industry Tradeshow</option>
     <option>Industry Conference </option>
     <option>Lifestyle Sponsorship</option>
     <option>Partner Event</option>
     <optgroup label="Private Event" class="normal">
    <option>Customer</option>
    <option>Internal</option>
    <option>AR/PR</option>
    <option>User Group</option>
    <option>Other Proprietary</option> 
     </optgroup>
     <option>Road Show/Seminar</option>
     <option>Virtual Event</option>
     <option>Webinar</option>
     <option>Training</option>
     </select></label></p>
        <p>Participation</p>
      <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p>Event Status</p>
    <p><label><select name="" class="search-form-select"><option>All</option></select></label></p>
    <p><input name="" type="button"  class="global-button" value="Search"/></p>
     </form>
   

<?php $this->placeholder('sidebar-search')->captureEnd() ?>
